export { default as AvatarSelector } from './AvatarSelector.vue'
export { default as BackToDashboard } from './BackToDashboard.vue'
export { default as ConfirmDialog } from './ConfirmDialog.vue'
export { default as MultiSelectTags } from './MultiSelectTags.vue'
export { default as SearchBar } from './SearchBar.vue'
export { default as SpecialityBadgeWithTooltip } from './SpecialityBadgeWithTooltip.vue'
export { default as UserAvatar } from './UserAvatar.vue'
